/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.dashj.java-conventions")
}

dependencies {
    implementation("com.google.guava:guava:27.1-android")
    testImplementation("junit:junit:4.12")
}

description = "dashj-bls"

java {
    withJavadocJar()
}
