/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "dashj-parent"
include(":dashj-core")
include(":dashj-bls")
include(":dashj-examples")
include(":dashj-tools")
include(":wallettemplate")
project(":dashj-core").projectDir = file("core")
project(":dashj-bls").projectDir = file("bls")
project(":dashj-examples").projectDir = file("examples")
project(":dashj-tools").projectDir = file("tools")
