/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.dashj.java-conventions")
}

dependencies {
    implementation(project(":dashj-core"))
    implementation("com.google.guava:guava:27.1-android")
    implementation("org.fxmisc.easybind:easybind:1.0.2")
    implementation("de.jensd:fontawesomefx:8.0.0")
    implementation("net.glxn:qrgen:1.3")
}

description = "dashj Wallet-Template"
