import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.dashj.java-conventions")
    kotlin("jvm") version "1.3.72"
    id("org.openjfx.javafxplugin") version("0.0.8")
}

javafx {
    version = "15"
    modules = listOf("javafx.base", "javafx.fxml", "javafx.controls")
}

repositories {
    mavenCentral()
}

dependencies {
    implementation(project(":core"))
    implementation(kotlin("stdlib-jdk8"))
    implementation("org.fxmisc.easybind:easybind:1.0.2")
    implementation("de.jensd:fontawesomefx:8.0.0")
    implementation("net.glxn:qrgen:1.3")
    implementation("com.google.guava:guava:30.0-jre")
    implementation("org.bouncycastle:bcprov-jdk15to18:1.63")
    implementation("org.jetbrains.kotlin:kotlin-gradle-plugin:1.4.10")
    compile("com.google.protobuf:protobuf-java:3.6.1")
}

description = "dashj Wallet-Template"