import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.dashj.java-conventions")
}

dependencies {
    implementation(project(":core"))
    implementation("net.sf.jopt-simple:jopt-simple:5.0.4")
    implementation("com.h2database:h2:1.3.167")
    compile("com.google.protobuf:protobuf-java:3.6.1")
    implementation("org.bouncycastle:bcprov-jdk16:1.45")
}

description = "dashj Tools"
repositories {
    mavenCentral()
}